#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#define APP_PCBA_CHANNEL_COUNT              8u
#define APP_PRESSURE_SENSOR_COUNT           14u
#define APP_TANK_COUNT                      6u

#define APP_PCBA_UART_BAUDRATE              115200u
#define APP_PC_LINK_JLINK_UART8_ENABLED     0u
#define APP_PC_LINK_JLINK_RTT_ENABLED       0u
#define APP_PC_LINK_JLINK_RTT_DEBUG_TEXT_ENABLED 0u
#define APP_PC_LINK_BRINGUP_ONLY_ENABLED    0u
#define APP_PC_LINK_UART_BAUDRATE           9600u
#define APP_PC_LINK_STATUS_PERIOD_MS        100u
#define APP_KEY1_HOLD_TO_MSC_MS             1500u
#define APP_VALVE1_0_1HZ_TEST_ENABLED       0u
#define APP_VALVE1_TEST_HALF_PERIOD_MS      5000u
#define APP_LT768_COLOR_BAR_TEST_ENABLED    0u
#define APP_LT768_FRAMEBUFFER_TEST_ENABLED  0u
#define APP_LT768_STRESS_TEST_ENABLED       0u

#define APP_PRESSURE_SCALE_PER_MMHG         1000u
#define APP_PRESSURE_50_MMHG                (50u * APP_PRESSURE_SCALE_PER_MMHG)
#define APP_PRESSURE_100_MMHG               (100u * APP_PRESSURE_SCALE_PER_MMHG)
#define APP_PRESSURE_150_MMHG               (150u * APP_PRESSURE_SCALE_PER_MMHG)
#define APP_PRESSURE_200_MMHG               (200u * APP_PRESSURE_SCALE_PER_MMHG)
#define APP_PRESSURE_250_MMHG               (250u * APP_PRESSURE_SCALE_PER_MMHG)
#define APP_PRESSURE_285_MMHG               (285u * APP_PRESSURE_SCALE_PER_MMHG)

#define APP_PRESSURE_STABLE_WINDOW_RAW      20u
#define APP_PRESSURE_STABLE_TIME_MS         1000u
#define APP_MPRLS_I2C_ADDRESS               0x18u
#define APP_MPRLS_PRESSURE_MAX_001MMHG      (300u * APP_PRESSURE_SCALE_PER_MMHG)
#define APP_MPRLS_OUTPUT_MIN_COUNTS         419430u
#define APP_MPRLS_OUTPUT_MAX_COUNTS         3774874u
#define APP_MPRLS_CONVERSION_DELAY_MS       6u
#define APP_AIRTIGHTNESS_HOLD_TIME_MS       5000u
#define APP_AIRTIGHTNESS_MAX_DROP_001MMHG   (5u * APP_PRESSURE_SCALE_PER_MMHG)
#define APP_PCBA_RESPONSE_TIMEOUT_MS        200u
#define APP_PCBA_WAKE_RESPONSE_TIMEOUT_MS   2000u
#define APP_SINGLE_PCBA_RESPONSE_TIMEOUT_MS 2000u
#define APP_PCBA_STANDBY_CURRENT_CHECK_MS   1000u
#define APP_PCBA_WORK_CURRENT_MEASURE_MS    0u
#define APP_PCBA_POWER_ON_DELAY_MS          2000u
#define APP_SINGLE_PCBA_POWER_ON_DELAY_MS   3000u
#define APP_PCBA_POST_WAKE_SETTLE_MS        300u
#define APP_PCBA_CURRENT_TEST_PERIOD_MS     250u
#define APP_PCBA_POWER_SWITCH_DELAY_MS      500u
#define APP_STAGE_SETTLE_TIMEOUT_MS         30000u
#define APP_RESULT_CONFIRM_KEY_DEBOUNCE_MS  50u
#define APP_SINGLE_TANK_SETTLE_MS           800u
#define APP_SINGLE_TANK_SAMPLE_INTERVAL_MS  50u
#define APP_SINGLE_TANK_SAMPLE_COUNT        3u
#define APP_SINGLE_TANK_FAST_REFILL_PERCENT 90u
#define APP_SINGLE_TANK_REFILL_PULSE_MS     120u
#define APP_SINGLE_TANK_RELIEF_PULSE_MS     80u
#define APP_SINGLE_TANK_REVERSE_GUARD_001MMHG (8u * APP_PRESSURE_SCALE_PER_MMHG)
#define APP_SINGLE_TANK_MAX_RUNTIME_MS      (10u * 60u * 1000u)
#define APP_SINGLE_TANK_MAX_REFILL_NO_RISE_COUNT 6u
#define APP_PRESSURE_HARD_LIMIT_ABS_001MMHG (295u * APP_PRESSURE_SCALE_PER_MMHG)
#define APP_PRESSURE_HARD_LIMIT_MARGIN_001MMHG (30u * APP_PRESSURE_SCALE_PER_MMHG)
#define APP_INIT_REFILL_MAX_RUNTIME_MS      (2u * 60u * 1000u)
#define APP_PRESSURE_INVALID_ABORT_MS       300u

#define APP_CURRENT_ADC_VREF_MV             3300u
#define APP_PCBA_CURRENT_AMP_GAIN           100u
/* In uA mode the eight 1k sense resistors are effectively shorted together by crosstalk. */
#define APP_PCBA_STANDBY_SHUNT_SINGLE_MOHM  1000000u
#define APP_PCBA_STANDBY_SHUNT_PARALLEL_COUNT 8u
#define APP_PCBA_STANDBY_SHUNT_MOHM         (APP_PCBA_STANDBY_SHUNT_SINGLE_MOHM / APP_PCBA_STANDBY_SHUNT_PARALLEL_COUNT)
#define APP_PCBA_CURRENT_ADC_AVERAGE_SAMPLES 4u
#define APP_PCBA_CURRENT_FILTER_SHIFT       2u
/* PB1 high enables the shared low-resistance current-sense branch for all 8 PCBA channels. */
#define APP_PCBA_50MA_SHUNT_MOHM            200u
/* 0.2R is in series with the shared 2300N NMOS; update Rds(on) from the actual BOM datasheet. */
#define APP_PCBA_50MA_NMOS_RDS_ON_MOHM      85u
#define APP_PCBA_STANDBY_CURRENT_MAX_UA     0u
#define APP_PCBA_WORK_CURRENT_MIN_UA        0u
#define APP_PCBA_WORK_CURRENT_MAX_UA        0u

#define W25Q128_TOTAL_BYTES                 (16u * 1024u * 1024u)
#define W25Q128_SECTOR_BYTES                4096u
#define W25Q128_PAGE_BYTES                  256u
#define MSC_BLOCK_BYTES                     512u
#define MSC_BLOCK_COUNT                     (W25Q128_TOTAL_BYTES / MSC_BLOCK_BYTES)

#endif
